name: Build POSPal
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build executable
        run: python build.py
        
      - name: Verify build
        run: |
          if not exist dist\POSPal.exe (
            echo "::error::Build failed - no executable generated"
            exit 1
          )
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: POSPal
          path: dist/
          retention-days: 3