name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: python build.py
        
      - name: Create Release
        uses: softprops/action-gh-release@v2  # Updated from v1
        with:
          files: |
            dist/POSPal.exe
            POSPal.html
            install_service.bat
            uninstall_service.bat
            README.txt