name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build executable
        run: |
          python -m pip install pyinstaller
          python build.py
          
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/POSPal.exe
            POSPal.html
            install_service.bat
            uninstall_service.bat
            README.txt
          body: ${{ github.event.head_commit.message }}